services:
  redis:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile.redis  # Specify the Dockerfile for Redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: vunderkids
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./vunderkids
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres
      - rabbitmq
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:1234@postgres:5432/vunderkids

  frontend:
    build:
      context: ./vunderkids-v2.1/webproject
    volumes:
      - games_volume:/frontend/dist/games/
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./letsencrypt:/var/www/letsencrypt
      - ./ssl:/etc/ssl/certs
      - games_volume:/usr/share/nginx/html/games/
    depends_on:
      - backend
      - frontend

volumes:
  redis_data:
  postgres_data:
  games_volume:
