version: "3"

services:
  redis:
    image: redis:alpine

  backend:
    build:
      context: ./vunderkids
    command: sh -c "gunicorn vunderkids.wsgi --bind 0.0.0.0:8000 & celery -A vunderkids worker --loglevel=info"
    volumes:
      - .:/code
      - sqlite_data:/code/db.sqlite3
    depends_on:
      - redis
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./vunderkids-v2.1/webproject
    volumes:
      - react_build:/react/dist
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./letsencrypt:/var/www/letsencrypt
      - ./ssl:/etc/ssl/certs
    depends_on:
      - backend
      - frontend

volumes:
  react_build:
  sqlite_data:
