name: Deploy Services

on:
  repository_dispatch:
    types: [backend-updated, frontend-updated]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Deployment Repo
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Clone Backend Repo
      run: |
        rm -rf vunderkids
        git clone --branch prod https://github.com/BekzhanK1/vunderkids.git vunderkids

    - name: Clone Frontend Repo
      run: |
        rm -rf vunderkids-v2.1
        git clone --branch prod https://github.com/talaboiling/vunderkids-v2.1.git vunderkids-v2.1

    - name: Copy .env File
      run: |
        cp .env vunderkids/vunderkids/.env  # Assuming .env is in vunderkids-prod directory

    - name: List Directories
      run: |
        ls -l
        ls -l vunderkids
        ls -l vunderkids/vunderkids
        ls -l vunderkids-v2.1

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        
    - name: Verify Docker Installation
      run: |
        docker --version
        docker-compose --version

    - name: Run Docker Compose
      run: |
        docker-compose down || true  # Stop any running containers
        docker-compose up --build -d
