name: Deploy Services

on:
  repository_dispatch:
    types: [backend-updated, frontend-updated]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Deployment Repo
      uses: actions/checkout@v4
      with:
        ref: prod

    - name: Clone Backend Repo
      run: |
        rm -rf vunderkids
        git clone --branch prod https://github.com/owner_username/vunderkids.git vunderkids

    - name: Clone Frontend Repo
      run: |
        rm -rf vunderkids-v2.1
        git clone --branch prod https://github.com/owner_username/vunderkids-v2.1.git vunderkids-v2.1

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Run Docker Compose
      run: docker-compose up --build -d
